### ISSUE TITLE
allowDuplicates ignored when lists get merged on login with mergeLastListOnLogin

### ISSUE THREAD

**Issue by aloco** [verbb/wishlist#89]
**Description**
It seem like `'allowDuplicates' => false` is ignored when using `'mergeLastListOnLogin' => true` - When a guest is having element x in his list and afterwards logs in to his account which already have element x in the list, the lists are merged but contains element x twice. 

**Steps to reproduce**
1. use `'allowDuplicates' => false` and `'mergeLastListOnLogin' => true`
1. login and add something to a wishlist
2. logout and add the same thing to the guest wishlist
3. login again, lists are merged, containing the element twice

**Additional info**
- Plugin version: 1.4.8
- Craft version: 3.6.16
- Multi-site: No

**Additional context**
just checked `consolidateListsToUser` and it doesn´t look like there is any check for `allowDuplicates`

**Comment by engram-design** [comment]
Fixed in [1.4.9](https://github.com/verbb/wishlist/releases/tag/1.4.9)

**Comment by aloco** [comment]
Hi, thank you for your fast reaction.

We applied your fixes but still experiencing some issues. The first thing I recognised is, that your SQL Query is not respecting table prefixes -> https://github.com/verbb/wishlist/commit/d121bc624f02934ec1e1925369b22328657b7d35#diff-aa159f9d60369d27015a11fbbc30e75f948166c17eaa0aaaa94ace85506c2d32R255-R271 

In our project, we have two types of wishlists (bookmarks and some kind of last viewed items). Each user should only have one instance of each type of whishlist. 
Currently we are seeing the following: The user is a guest and put some stuff inside his bookmark list. Afterwards the user is logging in and the list gets transferred from a guest list to his personal list ✅ Afterwards the user logs out. Again, as a guest user (a couple days later for instance) the user put some stuff into his bookmark list and loggs in again. The list gets merged but sometimes the user ends up with two instances of the same list type. Maybe that is because the query is not working as expected without the table prefixes.. 

I hope its clear what we would like to achieve 

thanks!

**Comment by engram-design** [comment]
Good point on the table prefix, I was trying to refactor the SQL to use Yii's Query Builder, but went for raw SQL instead. But completely forgot the prefix handling.

I've also added another fix for non-default wishlist types, which is probably the issue you're seeing.

To get this fix early, change your `verbb/wishlist` requirement in `composer.json` to:

```
"require": {
  "verbb/wishlist": "dev-craft-3 as 1.4.9",
  "...": "..."
}
```

Then run `composer update`. Let me know if that helps, otherwise I'll take another look.

**Comment by aloco** [comment]
Hi, 

it seems like the issues are now resolved. Thank you! Can you release this as a new version?

**Comment by engram-design** [comment]
Fixed in [1.4.10](https://github.com/verbb/wishlist/releases/tag/1.4.10)
